apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: eng114sharmake/sharmarkenginx

          ports:
            - containerPort: 80
          

          imagePullPolicy: Always
